import './bootstrap';
import 'bootstrap';
import {
    AlertTriangle,
    ArrowLeft,
    BarChart2,
    Bell,
    Building,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleArrowRight,
    CircleCheck,
    ClipboardCheck,
    Clock,
    Database,
    Edit,
    ExternalLink,
    FileDown,
    FileText,
    FolderOpen,
    FolderPlus,
    HandHeart,
    History,
    Home,
    IdCard,
    Layers,
    List,
    Lock,
    LogOut,
    Mail,
    MessageSquare,
    MessageSquarePlus,
    Network,
    PenLine,
    Pencil,
    Phone,
    Plus,
    Save,
    Search,
    Send,
    ShieldAlert,
    ShieldCheck,
    Target,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    Users,
    X,
    XCircle,
    createIcons,
} from 'lucide';

const icons = {
    'alert-triangle': AlertTriangle,
    'arrow-left': ArrowLeft,
    'bar-chart-2': BarChart2,
    bell: Bell,
    building: Building,
    calendar: Calendar,
    check: Check,
    'check-circle': CheckCircle,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'circle-arrow-right': CircleArrowRight,
    'circle-check': CircleCheck,
    'clipboard-check': ClipboardCheck,
    clock: Clock,
    database: Database,
    edit: Edit,
    'external-link': ExternalLink,
    'file-down': FileDown,
    'file-text': FileText,
    'folder-open': FolderOpen,
    'folder-plus': FolderPlus,
    'hand-heart': HandHeart,
    history: History,
    home: Home,
    'id-card': IdCard,
    layers: Layers,
    list: List,
    lock: Lock,
    'log-out': LogOut,
    mail: Mail,
    'message-square': MessageSquare,
    'message-square-plus': MessageSquarePlus,
    network: Network,
    'pen-line': PenLine,
    pencil: Pencil,
    phone: Phone,
    plus: Plus,
    save: Save,
    search: Search,
    send: Send,
    'shield-alert': ShieldAlert,
    'shield-check': ShieldCheck,
    target: Target,
    user: User,
    'user-check': UserCheck,
    'user-minus': UserMinus,
    'user-plus': UserPlus,
    users: Users,
    x: X,
    'x-circle': XCircle,
};

const renderLucideIcons = () => {
    if (typeof document === 'undefined') {
        return;
    }

    createIcons({
        icons,
        attrs: {
            'stroke-width': 1.75,
        },
    });
};

document.addEventListener('DOMContentLoaded', renderLucideIcons);
document.addEventListener('livewire:navigated', renderLucideIcons);
window.addEventListener('load', renderLucideIcons);

window.renderLucideIcons = renderLucideIcons;
