<?php

namespace Modules\Prestaciones\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Prestaciones\Models\Prestacion;

/**
 * Catálogo inicial de prestaciones de servicios sociales.
 *
 * Basado en la Guía de Prestaciones de Servicios Sociales y Educativos
 * del Ayuntamiento de Madrid (edición 2024), que recoge 112 prestaciones
 * organizadas en ocho objetivos generales.
 *
 * Seeder idempotente: usa updateOrCreate por código. Puede ejecutarse
 * múltiples veces sin duplicados ni errores.
 */
class PrestacionesSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->prestaciones() as $data) {
            $tiposCentro = $data['tipos_centro'] ?? [];
            unset($data['tipos_centro']);

            $prestacion = Prestacion::updateOrCreate(
                ['codigo' => $data['codigo']],
                $data
            );

            // Sincronizar tipos de centro
            $prestacion->tiposCentro()->delete();
            foreach ($tiposCentro as $tipo) {
                $prestacion->tiposCentro()->create(['tipo_centro' => $tipo]);
            }
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function prestaciones(): array
    {
        return [

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 01 — Acceso, información y valoración
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '010101',
                'nombre' => 'Servicio de Información, Valoración, Orientación y Asesoramiento (SIVOAS)',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0101',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Facilitar a los ciudadanos el acceso a los recursos y prestaciones del sistema de servicios sociales, garantizando el derecho a la información.',
                'descripcion' => 'Servicio de primera atención que informa, orienta y asesora a los ciudadanos sobre las prestaciones y recursos de servicios sociales municipales, autonómicos y estatales.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '010102',
                'nombre' => 'Información sobre prestaciones de otras administraciones',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0101',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Orientar a los ciudadanos hacia recursos y prestaciones de otras administraciones cuando la demanda no corresponde al ámbito municipal.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '010201',
                'nombre' => 'Valoración social',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0102',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Analizar la situación social de la persona y su entorno para identificar necesidades y establecer un plan de intervención.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado'],
            ],
            [
                'codigo' => '010301',
                'nombre' => 'Informe Social',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0103',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Documentar la situación social de una persona para facilitar el acceso a prestaciones o recursos, o a requerimiento de entidades externas.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado'],
            ],
            [
                'codigo' => '010302',
                'nombre' => 'Informe de habitabilidad',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0103',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Valorar las condiciones de habitabilidad de la vivienda de una persona a efectos de informes para el reagrupamiento familiar u otras gestiones administrativas.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '010401',
                'nombre' => 'Derivación y coordinación con otros servicios',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '01',
                'categoria_especifica' => '0104',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Coordinar la atención entre servicios sociales y otros sistemas (salud, educación, empleo, vivienda) para una intervención integral.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 02 — Inclusión social y empleo
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '020101',
                'nombre' => 'Atención en calle a personas sin hogar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0201',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['sin_hogar'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Detectar y atender a personas que viven en la calle, facilitando el acceso a recursos de alojamiento, alimentación y atención social.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_especializado', 'servicio_especifico'],
            ],
            [
                'codigo' => '020102',
                'nombre' => 'Alojamiento de urgencia para personas sin hogar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0201',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['sin_hogar'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar alojamiento inmediato a personas sin hogar en situación de emergencia, garantizando pernocta, higiene y manutención básica.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['albergue'],
            ],
            [
                'codigo' => '020103',
                'nombre' => 'Centro de acogida para personas sin hogar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0201',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['sin_hogar'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer alojamiento y atención integral a personas sin hogar, con seguimiento social orientado a la reinserción y autonomía.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['albergue'],
            ],
            [
                'codigo' => '020104',
                'nombre' => 'Piso de inserción para personas sin hogar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0201',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['sin_hogar'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar alojamiento en piso compartido con apoyo social individualizado para personas en proceso de inserción social.',
                'aportacion_usuario' => 'Gratuito o aportación según recursos',
                'activa' => true,
                'tipos_centro' => ['piso_insercion'],
            ],
            [
                'codigo' => '020201',
                'nombre' => 'Servicio de orientación e inserción sociolaboral',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0202',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['exclusion', 'migrantes'],
                'modalidades' => ['presencial', 'telematica'],
                'finalidad' => 'Acompañar a personas en situación de exclusión social en su proceso de incorporación al mercado laboral mediante orientación, formación y apoyo a la búsqueda de empleo.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado', 'servicio_especifico'],
            ],
            [
                'codigo' => '020202',
                'nombre' => 'Programa de empleo con apoyo',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0202',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'indirecta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['discapacidad', 'exclusion'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Facilitar el acceso al empleo ordinario de personas con discapacidad u otros colectivos en exclusión mediante apoyo personalizado en el puesto de trabajo.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['servicio_especifico'],
            ],
            [
                'codigo' => '020301',
                'nombre' => 'Ayuda de Emergencia Social (AES)',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0203',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Cubrir necesidades urgentes de subsistencia (alimentación, vivienda, suministros básicos) de personas o familias en situación de emergencia social.',
                'requisitos' => 'Situación de emergencia acreditada. Residencia en el municipio. Insuficiencia de recursos económicos.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '020302',
                'nombre' => 'Prestación Madrileña Complementaria (PMC)',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0203',
                'nivel_atencion' => 'asp',
                'competencia' => 'compartida',
                'forma_gestion' => 'directa',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['exclusion'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Complementar la Renta Mínima de Inserción (RMI) autonómica para garantizar ingresos mínimos de subsistencia a personas en situación de exclusión severa.',
                'requisitos' => 'Ser perceptor de RMI. Residencia en el municipio de Madrid. Acreditación de situación de exclusión.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '020401',
                'nombre' => 'Intervención social con población en riesgo de exclusión',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0204',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['exclusion', 'migrantes'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Acompañar y apoyar a personas en riesgo de exclusión social mediante un plan de intervención individualizado orientado a la mejora de su situación.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 03 — Familia, infancia y adolescencia
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '030101',
                'nombre' => 'Servicio de intervención y apoyo familiar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0301',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['familia', 'infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Apoyar a familias en situación de dificultad para fortalecer sus competencias parentales y mejorar el funcionamiento familiar, evitando la separación de menores.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'css_especializado'],
            ],
            [
                'codigo' => '030102',
                'nombre' => 'Ayuda a domicilio para familias con menores',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0301',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['familia', 'infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar apoyo domiciliario a familias con menores en situación de riesgo para mejorar el cuidado y atención de los niños en el hogar.',
                'aportacion_usuario' => 'Gratuito o copago según renta',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '030201',
                'nombre' => 'Atención a menores en situación de riesgo',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0302',
                'nivel_atencion' => 'especializada',
                'competencia' => 'compartida',
                'forma_gestion' => 'directa',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proteger a los menores en situación de riesgo o desamparo mediante actuaciones de prevención, detección y seguimiento de casos.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_especializado', 'servicio_especifico'],
            ],
            [
                'codigo' => '030202',
                'nombre' => 'Acogimiento familiar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0302',
                'nivel_atencion' => 'especializada',
                'competencia' => 'autonomica',
                'forma_gestion' => 'directa',
                'financiacion' => 'autonomica',
                'poblacion_destinataria' => ['infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Garantizar un entorno familiar a menores que no pueden vivir con su familia de origen, mediante la integración en una familia acogedora.',
                'aportacion_usuario' => 'Gratuito (con ayudas económicas a acogedores)',
                'activa' => true,
                'tipos_centro' => ['servicio_especifico'],
            ],
            [
                'codigo' => '030203',
                'nombre' => 'Acogimiento residencial de menores',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0302',
                'nivel_atencion' => 'especializada',
                'competencia' => 'autonomica',
                'forma_gestion' => 'mixta',
                'financiacion' => 'autonomica',
                'poblacion_destinataria' => ['infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar a menores en situación de desamparo un entorno residencial seguro con atención educativa y social integral.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['servicio_especifico'],
            ],
            [
                'codigo' => '030301',
                'nombre' => 'Programa de apoyo a la crianza y parentalidad positiva',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0303',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['familia', 'infancia'],
                'modalidades' => ['presencial', 'telematica'],
                'finalidad' => 'Fortalecer las competencias parentales de las familias para mejorar el cuidado y la educación de sus hijos, especialmente en etapas críticas del desarrollo.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'centro_dia_inf'],
            ],
            [
                'codigo' => '030401',
                'nombre' => 'Servicio de mediación familiar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0304',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['familia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Facilitar el diálogo y el acuerdo entre personas en conflicto familiar, especialmente en procesos de separación o divorcio con menores implicados.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'punto_encuentro'],
            ],
            [
                'codigo' => '030402',
                'nombre' => 'Punto de encuentro familiar',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0304',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['familia', 'infancia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Facilitar el ejercicio del régimen de visitas de menores con sus progenitores en un espacio neutral y supervisado por profesionales.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['punto_encuentro'],
            ],
            [
                'codigo' => '030501',
                'nombre' => 'Atención e intervención con adolescentes en riesgo',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '03',
                'categoria_especifica' => '0305',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['juventud'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Intervenir con adolescentes en situaciones de riesgo social (absentismo, conductas disruptivas, consumo de sustancias) mediante programas de atención especializada.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_especializado', 'centro_dia_inf'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 04 — Autonomía personal y vida independiente
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '040101',
                'nombre' => 'Servicio de Ayuda a Domicilio (SAD)',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '04',
                'categoria_especifica' => '0401',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores', 'dependencia', 'discapacidad'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Apoyar la permanencia en el domicilio de personas con limitaciones para la autonomía mediante atención personal, doméstica y apoyo psicosocial.',
                'requisitos' => 'Valoración de la situación funcional y social. Residencia en el municipio.',
                'aportacion_usuario' => 'Copago según baremo de renta',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '040102',
                'nombre' => 'Servicio de Ayuda a Domicilio intensivo',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '04',
                'categoria_especifica' => '0401',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar atención domiciliaria de alta intensidad horaria a personas con gran dependencia funcional que no pueden acceder a recursos residenciales.',
                'aportacion_usuario' => 'Copago según baremo de renta',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],
            [
                'codigo' => '040201',
                'nombre' => 'Programa de vida independiente para personas con discapacidad',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '04',
                'categoria_especifica' => '0402',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['discapacidad'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Apoyar a personas con discapacidad para vivir de forma autónoma en su domicilio, con asistencia personal y apoyo a la participación en la comunidad.',
                'aportacion_usuario' => 'Gratuito o copago según renta',
                'activa' => true,
                'tipos_centro' => ['servicio_especifico'],
            ],
            [
                'codigo' => '040301',
                'nombre' => 'Servicio de Teleasistencia domiciliaria',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '04',
                'categoria_especifica' => '0403',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'indirecta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores', 'dependencia', 'discapacidad'],
                'modalidades' => ['telefonica'],
                'finalidad' => 'Proporcionar atención inmediata a personas mayores o con discapacidad en caso de emergencia domiciliaria, favoreciendo su seguridad y permanencia en el domicilio.',
                'requisitos' => 'Mayores de 65 años o personas con discapacidad que vivan solas o con escaso apoyo familiar.',
                'aportacion_usuario' => 'Copago según renta o gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '040401',
                'nombre' => 'Adaptación del hogar para personas con discapacidad o dependencia',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '04',
                'categoria_especifica' => '0404',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['discapacidad', 'dependencia', 'mayores'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Financiar obras de adaptación de la vivienda y la adquisición de ayudas técnicas para personas con limitaciones funcionales que favorezcan su autonomía en el hogar.',
                'requisitos' => 'Acreditación de necesidad por valoración social. Titularidad o autorización del uso de la vivienda.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 05 — Atención a la dependencia
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '050101',
                'nombre' => 'Centro de Día para personas mayores',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0501',
                'nivel_atencion' => 'especializada',
                'competencia' => 'compartida',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['mayores', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer atención diurna integral a personas mayores con dependencia, facilitando su permanencia en el domicilio y apoyando a los cuidadores familiares.',
                'requisitos' => 'Valoración de dependencia (Ley 39/2006). Residencia en el municipio.',
                'aportacion_usuario' => 'Copago según renta y grado de dependencia',
                'activa' => true,
                'tipos_centro' => ['centro_dia'],
            ],
            [
                'codigo' => '050102',
                'nombre' => 'Centro de Día para personas con discapacidad',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0501',
                'nivel_atencion' => 'especializada',
                'competencia' => 'compartida',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['discapacidad', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar atención diurna especializada a personas con discapacidad con necesidades de apoyo en actividades de la vida diaria y participación social.',
                'aportacion_usuario' => 'Copago según renta',
                'activa' => true,
                'tipos_centro' => ['centro_dia'],
            ],
            [
                'codigo' => '050201',
                'nombre' => 'Residencia para personas mayores',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0502',
                'nivel_atencion' => 'especializada',
                'competencia' => 'compartida',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['mayores', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer alojamiento permanente y atención integral a personas mayores que no pueden ser atendidas en su domicilio por su situación de dependencia.',
                'requisitos' => 'Grado de dependencia II o III (Ley 39/2006). Informe de servicios sociales.',
                'aportacion_usuario' => 'Copago según renta (hasta el 75% de los ingresos)',
                'activa' => true,
                'tipos_centro' => ['residencia_mayores'],
            ],
            [
                'codigo' => '050301',
                'nombre' => 'Residencia para personas con discapacidad intelectual',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0503',
                'nivel_atencion' => 'especializada',
                'competencia' => 'autonomica',
                'forma_gestion' => 'mixta',
                'financiacion' => 'autonomica',
                'poblacion_destinataria' => ['discapacidad', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer atención residencial especializada a personas con discapacidad intelectual con necesidades de apoyo generalizadas.',
                'aportacion_usuario' => 'Copago según renta',
                'activa' => true,
                'tipos_centro' => ['residencia_disc'],
            ],
            [
                'codigo' => '050401',
                'nombre' => 'Programa de respiro para cuidadores familiares',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0504',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores', 'dependencia', 'discapacidad'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar descanso temporal a los cuidadores familiares principales de personas dependientes, mediante estancias temporales o atención diurna de la persona cuidada.',
                'aportacion_usuario' => 'Copago según renta',
                'activa' => true,
                'tipos_centro' => ['centro_dia', 'residencia_mayores'],
            ],
            [
                'codigo' => '050402',
                'nombre' => 'Apoyo económico a cuidadores no profesionales',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '05',
                'categoria_especifica' => '0504',
                'nivel_atencion' => 'asp',
                'competencia' => 'compartida',
                'forma_gestion' => 'directa',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['mayores', 'dependencia'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Compensar económicamente a los cuidadores familiares de personas dependientes que han reducido su actividad laboral para asumir el cuidado.',
                'requisitos' => 'Reconocimiento de dependencia. Cuidador conviviente o con vinculación familiar acreditada.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 06 — Urgencia social, emergencia y violencia de género
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '060101',
                'nombre' => 'Atención social de urgencia y emergencia',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0601',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Proporcionar atención social inmediata a personas o familias en situación de emergencia social (desahucios, catástrofes, situaciones críticas inesperadas).',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '060201',
                'nombre' => 'Atención integral a víctimas de violencia de género',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0602',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['vg'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Proporcionar atención social, psicológica y jurídica integral a víctimas de violencia de género, garantizando su seguridad y apoyando su proceso de recuperación.',
                'descripcion' => 'Incluye atención en el Centro de Atención a la Mujer (CAM), servicio telefónico de urgencias y derivación a recursos de acogida.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['centro_vg', 'css_especializado'],
            ],
            [
                'codigo' => '060202',
                'nombre' => 'Acogida de urgencia para víctimas de violencia de género',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0602',
                'nivel_atencion' => 'especializada',
                'competencia' => 'compartida',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['vg'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar alojamiento seguro e inmediato a víctimas de violencia de género y sus hijos/as en situación de riesgo.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['centro_vg'],
            ],
            [
                'codigo' => '060203',
                'nombre' => 'Piso de acogida de segunda fase para víctimas de VG',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0602',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['vg'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer alojamiento temporal a víctimas de violencia de género que han superado la fase de urgencia y están en proceso de recuperación e inserción social.',
                'aportacion_usuario' => 'Gratuito o aportación mínima',
                'activa' => true,
                'tipos_centro' => ['centro_vg', 'piso_insercion'],
            ],
            [
                'codigo' => '060301',
                'nombre' => 'Ayuda de emergencia por situación de violencia de género',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'garantizada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0603',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['vg'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar apoyo económico urgente a víctimas de violencia de género para hacer frente a las necesidades básicas inmediatas derivadas de la situación de violencia.',
                'requisitos' => 'Acreditación de la situación de violencia de género. Residencia en el municipio.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['centro_vg', 'css_general'],
            ],
            [
                'codigo' => '060302',
                'nombre' => 'Ayuda económica de emergencia social',
                'tipo_prestacion' => 'economica',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '06',
                'categoria_especifica' => '0603',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Cubrir necesidades básicas urgentes (alimentación, suministros, vivienda) de personas o familias que se encuentran en situación de emergencia social sobrevenida.',
                'requisitos' => 'Situación de emergencia acreditada. Residencia en el municipio. Insuficiencia de recursos económicos.',
                'aportacion_usuario' => 'No procede (prestación económica)',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 07 — Desarrollo comunitario
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '070101',
                'nombre' => 'Animación sociocultural y desarrollo comunitario',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '07',
                'categoria_especifica' => '0701',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Promover la participación activa de los vecinos en la vida comunitaria y el fortalecimiento del tejido social en los barrios mediante actividades y proyectos participativos.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '070201',
                'nombre' => 'Programa de convivencia intercultural y mediación comunitaria',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '07',
                'categoria_especifica' => '0702',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['migrantes', 'poblacion_general'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Fomentar la convivencia y la cohesión social en comunidades con diversidad cultural mediante mediación, espacios de encuentro y programas de sensibilización.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '070301',
                'nombre' => 'Apoyo y fomento del voluntariado social',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '07',
                'categoria_especifica' => '0703',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['poblacion_general'],
                'modalidades' => ['presencial', 'telematica'],
                'finalidad' => 'Promover y coordinar la participación voluntaria de ciudadanos en actividades de apoyo a personas vulnerables, fomentando la solidaridad y el compromiso social.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_general'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // OBJETIVO 08 — Participación social, cultura y ocio
            // ═══════════════════════════════════════════════════════════════

            [
                'codigo' => '080101',
                'nombre' => 'Actividades culturales y de ocio para personas mayores',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '08',
                'categoria_especifica' => '0801',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer actividades culturales, recreativas y de ocio a personas mayores para favorecer su participación social y el envejecimiento activo.',
                'aportacion_usuario' => 'Gratuito o precio simbólico',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '080201',
                'nombre' => 'Programa de envejecimiento activo y saludable',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '08',
                'categoria_especifica' => '0802',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Promover el envejecimiento activo y saludable de las personas mayores mediante programas de actividad física, prevención de la soledad y mantenimiento de capacidades cognitivas.',
                'aportacion_usuario' => 'Gratuito o copago reducido',
                'activa' => true,
                'tipos_centro' => ['css_general', 'servicio_especifico'],
            ],
            [
                'codigo' => '080301',
                'nombre' => 'Actividades deportivas y de actividad física adaptada',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '08',
                'categoria_especifica' => '0803',
                'nivel_atencion' => 'asp',
                'competencia' => 'municipal',
                'forma_gestion' => 'directa',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['mayores', 'discapacidad'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Ofrecer actividades deportivas y de actividad física adaptadas a las condiciones de las personas mayores o con discapacidad para mejorar su salud y calidad de vida.',
                'aportacion_usuario' => 'Gratuito o precio reducido',
                'activa' => true,
                'tipos_centro' => ['servicio_especifico'],
            ],

            // Prestaciones adicionales de atención a migrantes y LGTBI
            [
                'codigo' => '020402',
                'nombre' => 'Atención social a personas migrantes y solicitantes de asilo',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0204',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'cofinanciada',
                'poblacion_destinataria' => ['migrantes'],
                'modalidades' => ['presencial'],
                'finalidad' => 'Proporcionar atención social integral a personas migrantes y solicitantes de asilo, facilitando su acceso a derechos y su integración social.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_especializado', 'servicio_especifico'],
            ],
            [
                'codigo' => '020403',
                'nombre' => 'Atención social a personas LGTBI+ en situación de vulnerabilidad',
                'tipo_prestacion' => 'servicio',
                'nivel_garantia' => 'condicionada',
                'objetivo_general' => '02',
                'categoria_especifica' => '0204',
                'nivel_atencion' => 'especializada',
                'competencia' => 'municipal',
                'forma_gestion' => 'mixta',
                'financiacion' => 'local',
                'poblacion_destinataria' => ['lgtbi'],
                'modalidades' => ['presencial', 'telefonica'],
                'finalidad' => 'Proporcionar atención social y apoyo a personas LGTBI+ en situación de vulnerabilidad o exclusión, especialmente jóvenes y mayores.',
                'aportacion_usuario' => 'Gratuito',
                'activa' => true,
                'tipos_centro' => ['css_especializado', 'servicio_especifico'],
            ],
        ];
    }
}
